### ISSUE TITLE
Seperate make hack void email addresses?

### ISSUE THREAD

**Issue by mbainrot** [makehackvoid/committee#11]
Was wondering whether it would be worth looking at setting up seperate emails for announcements (e.g. reply to emails for stuff like AGM announcements)

This is mainly to make it easier to pick out emails related to MHV from the crap that comes through normally in my inbox by having it at a seperate inbox. (((EDIT))) (This would be an alternative to requiring people to insure that a particular string is included in the body of the email so that my charly foxtrot of a filter setup can find it and mark it)

Additionally we could back it into like a ticket system? so then any replies or responses are recorded (but I would imagine in the situe of privacy not publically avialable but there is a whole pleferoa of other issues that could arrise (such as FOI, etc)) This would have the added benifit that if the person behind the inbox is sick, offline, on holiday, etc then emails don't go unanswered.

A bit of in between work cycle mental diarrhea so please pardon the scatter brain/short hand/shit spelling

**Comment by brendam** [comment]
My idea of using github was as a quick and easy way to have a kind of ticketing system.

 I'm negotiating with GitHub about getting us some private repositories, and they've given us three months bronze membership for now. So we can setup a private 'committee-private' repository where you could include more details about emails in the issues than would be appropriate in a public repo like this one. I'm not sure we have enough volume of email to make it worth the trouble of setting up our own separate ticketing system. 

secretary (at) make hack void (dot) com already exists, but I'm guessing people didn't send the emails your worrying about to that? (do you get the emails sent to secretary (at) make hack void (dot) com ?)

**Comment by mbainrot** [comment]
just pinged the email and doesn't appear to work :S 

Iirc github does have an api so we might be able to get emails to secutary to automatically generate an issue in github.

If i get time i will have a look at it to see what is involved (prob will have to sort out a functional userid etc)

**Comment by brendam** [comment]
@deece can you please check the setup of the secretary email address?

**Comment by deece** [comment]
It's currently forwarded to Lachlan as the insurance invoices never made it to the committee and he volunteered to follow up.

**Comment by brendam** [comment]
@mbainrot can I close this now?

**Comment by mbainrot** [comment]
Yea that's fine
