### ISSUE TITLE
Additional agenda item for AGM

### ISSUE THREAD

**Issue by brendam** [makehackvoid/committee#12]
@mbainrot can you please add this to the AGM minutes, we need to vote on this each year. Although not sure if it should be committee meeting or AGM?
- Statement of Non-Profit Tax Exempt Status
  
  Annual review of income tax status:
  As per the ATO document "Income tax guide for non-profit
  organisations" (NAT 7967), Make, Hack, Void, Inc. is a Community
  Service Organisation. We are a non-profit association and we provide
  facilities for the benefit or welfare of the community (specifically,
  a community workshop.) Therefore we self-assess as exempt from income
  tax.

**Comment by mbainrot** [comment]
Okies I can do that

Kindest Regards
Max Bainrot
mbainrot@gmail.com

This email was sent from my smartphone please pardon any auto correct brain
farts or excessive brevoty
