### ISSUE TITLE
Security system down

### ISSUE THREAD

**Issue by deece** [makehackvoid/committee#14]
I received a call from Security One today, it seems our system has been disconnected.

I can't make it out during business hours at the moment due to work commitments, is anyone else willing to attend for them to send a technician out?

It might also be worth having a look to see if it something trivial like the power pack has been knocked loose.

**Comment by devdsp** [comment]
It's likely this is because MTA disabled any phone lines they had at the DBP and one of them was used for the BTB function on the alarm. If this is the case we may be able to get it hooked in to our phone line, but only if it doesn't compete with the ADSL.

**Comment by mbainrot** [comment]
Provided there is appropriate filters I would imagine it would be fine.

Though do we actually have a phone service or is our 'DSL naked?

**Comment by deece** [comment]
Did we have an ATA on the shelf? If so, we could use that to provide phone access for it. I _think_ most ATAs support modem/fax devices.

**Comment by mbainrot** [comment]
Depends on the make and brand :) most of them in my experience
"""support""" fax but fail at it badly

I am watching this space because I have a simular issue, my alarm's only
means to the outside world is a 65 meter long length of milspec 10gbe
multimode fibre :)

**Comment by brendam** [comment]
shall I close this?

**Comment by deece** [comment]
I don't think so, unless the committee is happy that we not have a functioning security system until we move (in which case, I think we are obliged to notify the insurance company).

In the meantime, I suggest we commission the wireless system that James donated the other day.

**Comment by brendam** [comment]
@deece can you assign yourself to this task then? Either to do it or find a member who is interested in doing it?

**Comment by mbainrot** [comment]
What about contacting the mob that does our Voip. They should have encountered a few back to base ones. My Linksys ata seems to work fine with sending basic faxes but fails pretty badly at higher quality ones.

Most of it is to-do with the codecs used and the quality of the provider.

**Comment by brendam** [comment]
Just received invoice for 3 months service from 11 August 2013. This suggests that I've missed an invoice in between? Although it doesn't seem to have any arrears.  Can someone please volunteer to take on sorting this out. Will need to follow up with security company, I'll email the contact details and invoice to whoever volunteers.

**Comment by deece** [comment]
Hi Brenda,

Could you please send me the invoice so I can add it to the records?

It may be best to send it to the PO Box (currently my personal one: PO Box 5040 Braddon ACT 2612), that way I’ll scan them as soon as they come in.
