### ISSUE TITLE
Organize utilities for new location

### ISSUE THREAD

**Issue by B0073D** [makehackvoid/committee#20]
This includes water and electricity

**Comment by brendam** [comment]
now that this doesn't have to happen _this week_ (ACTPG are leaving power and water on over the weekend) I'd like to pass it back for someone else to do.

**Comment by brendam** [comment]
I've finished this :-)  We don't need to do anything, ACTPG has decided it's easiest fro them to pass the bills onto us and for use to pay them instead of setting up accounts.
