### ISSUE TITLE
Risk Assessment and Chemicals register

### ISSUE THREAD

**Issue by brendam** [makehackvoid/committee#21]
old version for Downer space: http://makehackvoid.com/community/risk-assessment.html

newer versions on wiki - need to consolidate these:

https://wiki.makehackvoid.com/tech_docs:risk_assessment
https://wiki.makehackvoid.com/policy:draft_risk_assessment
https://wiki.makehackvoid.com/policy:draft_risk_assessment_register
https://wiki.makehackvoid.com/howto:safety:risk_assessment

**Comment by brendam** [comment]
working bee has happened, Janet writing up.

**Comment by jamiereid** [comment]
closing issue as this repo will be archived.
