### ISSUE TITLE
Change Signatories on ANZ Bank account

### ISSUE THREAD

**Issue by brendam** [makehackvoid/committee#3]
Needs all current people who can sign to go to Belconnen ANZ to sign new signature card.

**Comment by brendam** [comment]
@deece @devdsp any idea when you can go and sign?

**Comment by deece** [comment]
Getting out of the city during business hours is hard for me. Do you have a contact so I can arrange signing at the city (like I did the first time around)?

**Comment by devdsp** [comment]
I'll try to head in today.

**Comment by brendam** [comment]
@deece they say it will take 3-4 business days each way to send it, so if there is any way you can get to Belconnen it would be good. They are open until 5pm on Friday if that helps. If you can't then I can give you the name of the person to contact. Best to wait until @devdsp has signed though.

**Comment by devdsp** [comment]
I've signed now. We need to get the letter redrawn and co-signed. @deece if you want to do the signing in civic you'll need to email Nav navleen.malhotra@anz.com and tell him which branch (there're two in civic) you prefer and take in the new letter.

**Comment by deece** [comment]
I've contacted Naveen - where do I get the letter from?

**Comment by brendam** [comment]
@devdsp has the letter. It is just a cover letter asking them to remove people and add me, and a printout of the minutes that confirm that (although they may have that from @devdsp already).  It needs to be signed by two existing signatories. So if you are likely to see @nixotic before @devdsp then @devdsp or I can give you a version to print.

**Comment by deece** [comment]
> @devdsp has the letter. It is just a cover letter asking them to remove
> people and add me, and a printout of the minutes that confirm that
> (although they may have that from @devdsp already.  It needs to be signed
> by two existing signatories. So if you are likely to see @nixotic before
> @devdsp then @devdsp or I can give you a version to print.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/makehackvoid/committee/issues/3#issuecomment-17769114

If someone is at MHV, please print, sign & drop the aforementioned letter
in my locker, then let me know.

I'll come past on my way home & take in to ANZ the next day.

**Comment by devdsp** [comment]
The letter is signed and in your locker.

**Comment by brendam** [comment]
@deece have you been able to get to the bank yet?

**Comment by deece** [comment]
I've got the letter, was busy with reno on Friday, and am sick today. Should hopefully get in tomorrow.

**Comment by brendam** [comment]
Sorry to hear you're sick, get well soon!

**Comment by brendam** [comment]
I now have readonly access online access to the MHV account, and may well leave it at that for now. I'll call the business banking if/when I feel inspired. We don't have many payments to authorise, and the other signatories can do that instead.
