### ISSUE TITLE
2 door display fridge

### ISSUE THREAD

**Issue by brendam** [makehackvoid/committee#8]
Committee approved purchase of 2 door display fridge.

still being worked out:
- Transport to space
- Location in space

**Comment by devdsp** [comment]
Fridge has been transported to the space.
Waiting for it to settle before placing it and switching it on.

I've filled out the expense claim form and have it in my bag.

**Comment by devdsp** [comment]
Paperwork is in and I've requested the transfer from the bank.
Waiting for someone to log in and authorise it.

**Comment by brendam** [comment]
Entered in mhv accounts.
Still needs @deece or @nixotic to authorise bank transfer.

**Comment by deece** [comment]
Brenda Moon notifications@github.com wrote:

> Entered in mhv accounts.
> Still needs @deece or @nixotic to authorise bank transfer.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/makehackvoid/committee/issues/8#issuecomment-16993709

## done

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by brendam** [comment]
@devdsp I think this can be closed?

**Comment by devdsp** [comment]
Yup. As much as what the committee can do has been done.
